// #define MASTER_LEFT
#define MASTER_RIGHT

#define TAPPING_TERM 200

#define MOUSEKEY_DELAY 20
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_TIME_TO_MAX 10

#define RGBLIGHT_LAYERS
#define RGBLIGHT_SPLIT
#define RGBLIGHT_DISABLE_KEYCODES

#define RGBLIGHT_DEFAULT_HUE 0
#define RGBLIGHT_DEFAULT_SAT 0
#define RGBLIGHT_DEFAULT_VAL 0

#define ENCODER_RESOLUTION 2
